# Generated by Django 4.2.4 on 2023-09-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_material_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('newsandevents', models.CharField(max_length=1000)),
            ],
        ),
    ]
